### ISSUE TITLE
Cloning custom-project clones v5.0 instead of v4.3.0

### ISSUE THREAD

**Issue by javac9** [opencrx/opencrx-custom#2]
It seems that the `git clone` command from here: https://github.com/opencrx/opencrx-documentation/blob/master/Sdk/CustomProject.md#checkout-and-build-the-sample-custom-project
actually clones the version 5 of the project.

I saw v5.0 related error after executing `gradle clean` on such a cloned project. After downloading v4.3.0 manually, I was able to clean and assemble the custom project.

**Comment by wfro64** [comment]
After cloning you have to checkout with the version tag (e.g. opencrx-v4.3.0). Otherwise you work on master.

See updated documentation https://github.com/opencrx/opencrx-documentation/blob/master/Sdk/CustomProject.md
